# Generated by Django 4.2.5 on 2023-09-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepositoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio', models.CharField(max_length=40)),
                ('fechaEntrega', models.DateField()),
            ],
        ),
    ]
